services:
  apache:
    image: ghcr.io/ifpb/new_wave/wave-apache
    # build:
    #   context: .
    #   dockerfile: Dockerfile.server
    container_name: server
    #ports:
    #- "80:80"
    # network_mode: none

  client_container:
    image: ghcr.io/1valcl3b/last_wave-client:latest
    #build:
      #context: ../../../wave-client
      #dockerfile: Dockerfile
    container_name: client
    privileged: true
    #environment:
      #- DISPLAY=${DISPLAY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/home/vlc/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - apache
      # - prometheus
      # - cadvisor
      # - redis
    network_mode: none

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wave_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - wave_net
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    networks:
      - wave_net


networks:
  wave_net:
    external: true
